# Virtual Hypixel Configuration File

# Your Account
account:
  email: 
  password: 
  auth: microsoft # microsoft or mojang account
  hypixelApiKey: 

# Options for filtering packets
packet:
  enableMods: true # enables mods like freelook
  deObf: true # shows player names in duels

# Modules to enable
modules:
  packetFilter: true
  playerModule: true
  fpsBoost: true
  betterPing: true
  betterInvis: false
  autoGG: false
  playProtection: false # /play protection - asks you to confirm a /play command if you're in game
  autoTip: true

# Options for the settings window
inGameSettings:
  open: "/virtual"

# FPS boost options
fpsBoost:
  particles: false
  fireworks: false
  showRedstone: false # show redstone particles (this is the particle above someone's head when they have tnt in bedwars)

# BetterPing options
betterPing:
  interval: 5000

# AutoGG Options
autoGG:
  message: #list of messages to be sent
    - /ac gg
  delay: 100 # delay between the messages (in ms)

# AutoTip Options
autoTip:
  interval: 5 # send /tip all every N minutes

stats:
  overall: true # true or false, show overall stats instead of gamemode specific stats (overall bedwars instead of solo bedwars, etc.)
  # Customization for the stats shown is also possible(check src/proxy/interfaces/configInterface.ts for accepted keys
  wins: GOLD #-> makes the amount of wins shown in GOLD
  losses: RED
  wlr: GOLD
  kills: GOLD
  fkills: GOLD
  deaths: RED
  fdeaths: RED
  kdr: GOLD
  ws: GOLD
  bws: GOLD
  fkdr: GOLD

# Other options
other:
  showCorrectNameAndSkin: true # Shows the name and skin of your opponent in a duels mode
  requestTimeout: 10000 # how many MS a network request is allowed to take, only change this if you have to
  discordbotToken:  # token for the discord bot
  discordguild_id:  # guild id for the discord bot
  discordingamechat:  # channel id for the discord bot
  discordsessionchat:  # sessionchat id for the discord bot